### ISSUE TITLE
Does the Action Handle a Directory of JSON Files or Just a Single File?

### ISSUE THREAD

**Issue by ChrisWiles** [taahamahdi/i18n-ai-translate#254]
Hi @TaahaMahdi,  

Does this action handle a directory of JSON files (`*.json`) or just a single JSON file at a time?  

I’m working with multiple files in a folder and want to know if it supports that or if it needs customization.  

Thanks!

**Comment by taahamahdi** [comment]
It should handle all JSONs in the same directory. Let me know if you encounter any issues.

**Comment by ChrisWiles** [comment]
`npx i18n-ai-translate diff --before test_before --after test`

Where each is a folder with json files. It fails. `Invalid input JSON: Error: EISDIR: illegal operation on a directory, read`

**Comment by taahamahdi** [comment]
The arguments to before and after should be the source JSON file, such as en.json and en-updated.json. It will use the directory they're in

**Comment by ChrisWiles** [comment]
![Screenshot 2024-12-24 at 1 41 04 PM](https://github.com/user-attachments/assets/8a978f91-e83a-4837-adf7-bda0de9034bd)
![Screenshot 2024-12-24 at 1 41 44 PM](https://github.com/user-attachments/assets/71061b95-5bb4-47bc-8191-338c4bfc7436)

There is no source json file. I have a folder of json files which are passed to i18next int

**Comment by taahamahdi** [comment]
Ah, I understand now. The CLI doesn't support your format, but I can look into adding it if you're interested. In the meantime, there are some exported methods you can test it with if you import the package as a dependency.

**Comment by ChrisWiles** [comment]
I'm trying to work around the issue by calling the `diff` function on each file, but I'm getting the following error:

```text
Input files are not in the same directory
```

### Code Reference
From the file [[translate.ts](https://github.com/taahamahdi/i18n-ai-translate/blob/3701b59e18f2a04467e5c0a37d90f041e054d8e9/src/translate.ts#L828)](https://github.com/taahamahdi/i18n-ai-translate/blob/3701b59e18f2a04467e5c0a37d90f041e054d8e9/src/translate.ts#L828):

```typescript
// Ensure they're in the same path
if (path.dirname(beforeInputPath) !== path.dirname(afterInputPath)) {
    console.error("Input files are not in the same directory");
    return;
}
```

### Problem
It's unclear to me why this is an issue with my paths. Wouldn't they always be different since we copy the directory?

Here's the error I get after modifying one file, `addresses.json`, and running the workflow:

```text
Processing file: src/localization/en/addresses.json
Relative Path: addresses.json
Before File Path: src/localization/en-before/addresses.json
After File Path: src/localization/en/addresses.json
npm warn exec The following package was not found and will be installed: i18n-ai-translate@2.0.8
Input files are not in the same directory
Translation completed successfully for src/localization/en/addresses.json
```

### Workflow File

Below is the workflow file I used to test the process:

```yaml
name: 'i18n-ai-translate'

on:
  pull_request:
    # Only run if something changed in src/localization/en
    paths:
      - 'src/localization/en/*.json'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Identify changed JSON files
        id: changed_json_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }} -- 'src/localization/en/*.json')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed JSON files found. Exiting."
            echo "changed_files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Changed JSON files:"
          echo "$CHANGED_FILES"
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create folder for base branch ("before")
        if: ${{ steps.changed_json_files.outputs.changed_files != '' }}
        run: mkdir -p src/localization/en-before

      - name: Copy base-branch versions into "before"
        if: ${{ steps.changed_json_files.outputs.changed_files != '' }}
        run: |
          while read -r file; do
            RELATIVE_PATH="${file#src/localization/en/}"
            mkdir -p "src/localization/en-before/$(dirname "$RELATIVE_PATH")"
            git checkout origin/${{ github.event.pull_request.base.ref }} -- "$file"
            cp "$file" "src/localization/en-before/$RELATIVE_PATH"
            git checkout ${{ github.event.pull_request.head.sha }} -- "$file"
          done <<< "${{ steps.changed_json_files.outputs.changed_files }}"

      - name: Diff-based translation for each file
        if: ${{ steps.changed_json_files.outputs.changed_files != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          while read -r file; do
            RELATIVE_PATH="${file#src/localization/en/}"
            BEFORE_FILE="src/localization/en-before/$RELATIVE_PATH"
            AFTER_FILE="$file"
            if [[ ! -f "$BEFORE_FILE" ]]; then
              echo "Error: Before file does not exist at $BEFORE_FILE"
              exit 1
            fi
            if [[ ! -f "$AFTER_FILE" ]]; then
              echo "Error: After file does not exist at $AFTER_FILE"
              exit 1
            fi
            npx i18n-ai-translate diff \
              --before "$BEFORE_FILE" \
              --after  "$AFTER_FILE" \
              --engine "chatgpt" \
              --model "gpt-4o" \
              --api-key "$OPENAI_API_KEY" \
              --input-language "en" \
              --verbose
          done <<< "${{ steps.changed_json_files.outputs.changed_files }}"

      - name: Delete en-before directory
        if: ${{ steps.changed_json_files.outputs.changed_files != '' }}
        run: rm -rf src/localization/en-before

      - name: Commit and Push changes
        if: ${{ steps.changed_json_files.outputs.changed_files != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update i18n translations [skip ci]'
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Could you please clarify why this error occurs and how to resolve it? Let me know if you need any other details!
